add_newline = false

# A minimal left prompt
format = """$python$container$directory$character$distrobox"""

# move the rest of the prompt to the right
#right_format = """$status$git_branch${custom.git_status_dirty}$git_status"""
right_format = """$status$cmd_duration$git_branch${custom.git_status_dirty}$git_status"""

[custom.distrobox]
command = """
if [[ -n $DISTROBOX_ENTER_PATH ]]; then
 echo "ó°†§ $(cat /etc/os-release | grep PRETTY_NAME | cut -d '"' -f 2)"
fi
"""
when = "test -n $(DISTROBOX_ENTRY_PATH)"
format = " $output"

[container]
symbol = 'ðŸ“¦'
format = '[$symbol \[$name\]]($style) '

[character]
success_symbol = "[â¯](purple)[â¯](cyan)"
error_symbol = "[â¯](yellow)[â¯](red)"
vimcmd_symbol = "[â®](purple)[â®](cyan)"
# success_symbol = "[â¨ ](purple)"
# error_symbol = "[â¨ ](red)"
# vicmd_symbol = "[âª»](yellow)"

[python]
format = '\($virtualenv\) '

[directory]
style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = ' [$branch]($style)'
style = 'green'

[git_status]
format = '( [\[$ahead_behind$stashed\]]($style))'
style = "cyan"
stashed = "â‰¡"
ahead = "â‡¡${count}"
behind = "â‡£${count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "â€¢"
style = "white"
format = "[$symbol]($style)"
shell = ["sh"]

[cmd_duration]
format = ' [$duration]($style)'

[line_break]
disabled = true

[status]
disabled = false
symbol = ' âœ˜'
